[package]
name = "lines_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
once_cell = "1.10.0"
structopt = "0.3.26"
walkdir = "2.3.2"
